plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
theme: jekyll-theme-tactile
title: Oliver Delgado
description: My quick and dirty portfolio :-)
google_analytics: G-3PXX5ZXE9X